### ISSUE TITLE
make run doesn't  work on mac

### ISSUE THREAD

**Issue by MichaelClifford** [containers/ai-lab-recipes#279]
Following the README instructions on mac, I ran: 

```
make -f Makefile build && make -f Makefile run
```
build step completes. And the it runs:

```
cd ../../models && \
        podman run -it -d -p 8001:8001 -v ./mistral-7b-instruct-v0.1.Q4_K_M.gguf:/locallm/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf:ro -e MODEL_PATH=/locallm/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf -e HOST=0.0.0.0 -e PORT=8001 quay.io/ai-lab/model_servers/llamacpp_python:latest
```
The container instantly crashes with:

```
llama_model_load: error loading model: failed to open /locallm/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf: Permission denied
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/__main__.py", line 88, in <module>
    main()
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/__main__.py", line 74, in main
    app = create_app(
          ^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 138, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/app.py", line 75, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/server/model.py", line 138, in load_llama_from_model_settings
    _model = create_fn(
             ^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/llama.py", line 314, in __init__
    self._model = _LlamaModel(
                  ^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/llama_cpp/_internals.py", line 55, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /locallm/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf
```

 I think that the it might be an issue with the `BIND_MOUNT_OPTION` in the model_severs common Makefile.

**Comment by MichaelClifford** [comment]
Update:

This works as long as I download the model with `make download`.

**Comment by MichaelClifford** [comment]
Update: 

Thanks to @Gregory-Pereira help, we were able to figure out that this was ultimately a user error on my part. 

Using the `Z` bind mount option when running the model server, which I've been doing for the last few months, adds a `security.selinux` tag to all of the files on the localhost that are part of the mounted directory. This prevented the use of the `ro` option enforced by the makefile.

Looks like this issue can be avoided, by only using `ro` and not `Z` when using volume mounts on Mac.
